FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup -g 1001 -S payvio && adduser -S payvio -u 1001
COPY --from=builder /app/public ./public
COPY --from=builder --chown=payvio:payvio /app/.next/standalone ./
COPY --from=builder --chown=payvio:payvio /app/.next/static ./.next/static
USER payvio
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
